### ISSUE TITLE
Update BouncyCastle in org.web3j:core:4.8.7-android

### ISSUE THREAD

**Issue by mahdit8** [hyperledger/web3j#2008]
# _Issue_title_
After attempting to use another library that utilizes BouncyCastle version [1.77](https://www.bouncycastle.org/latest_releases.html), I encountered a dependency issue. Upon inspecting the dependency tree for the latest Android version of `org.web3j:core:4.8.7-android`, I observed the following dependency. I believe updating to a newer version is necessary to accommodate the new version of BouncyCastle.

```
+--- org.web3j:core:4.8.7-android
|    +--- org.web3j:abi:4.8.7-android -> 4.9.5
|    |    \--- org.web3j:utils:4.9.5
|    |         \--- org.bouncycastle:bcprov-jdk15on:1.68
```

## _Issue_description_
Leads to build error:
`Caused by: java.lang.RuntimeException: Duplicate class org.bouncycastle.LICENSE found in modules jetified-bcprov-jdk15on-1.68 (org.bouncycastle:bcprov-jdk15on:1.68) and jetified-bcprov-jdk18on-1.77 (org.bouncycastle:bcprov-jdk18on:1.77)`

**Comment by BradMoeller** [comment]
Also ran into this issue after updating the latest version of wallet connect kotlin: https://github.com/WalletConnect/WalletConnectKotlinV2

**Comment by TalhaAli00** [comment]
@BradMoeller 
There's a [new release](https://github.com/WalletConnect/WalletConnectKotlinV2/releases/tag/BOM_1.31.1) of WalletConnect which resolves this issue on Android

**Comment by NickSneo** [comment]
Closing as a hotfix is provided in release [web3j-4.9.8-hotfix](https://github.com/hyperledger/web3j/releases/tag/v4.9.8-hotfix) 
Thanks @TalhaAli00 for contributing.
