### ISSUE TITLE
Build fails due to dependency jc-kzg-4844 since version 4.11.0

### ISSUE THREAD

**Issue by michaelnetter** [hyperledger/web3j#2013]
# _Issue_title_
Build fails due to dependency jc-kzg-4844 since version 4.11.0

## _Issue_description_
I'm using web3j as a dependency in a maven project.
Since version 4.11.0, I am unable to build the project. The error message is the following:

> [ERROR] Failed to execute goal on project siwe-java: Could not resolve dependencies for project com.moonstoneid:siwe-java:jar:1.0.5: tech.pegasys:jc-kzg-4844:jar:0.8.0 was not found in https://repo1.maven.org/maven2 during a previous attempt.

It seems the issue is that the dependency **jc-kzg-4844** is not available on maven central but only in [this](https://cloudsmith.io/~consensys/repos/maven/packages/detail/maven/jc-kzg-4844/0.8.0/a=noarch;xg=tech.pegasys/) third party repository.

This puts developers who use web3j in a difficult spot. They need to either

- add the repo to their Maven settings.xml -> Must be done by every developer.
- add the repo to the pom.xml -> URL is hardcoded in the project forever. If the URL changes, this must be changed manually.

## _Issue_context_
The issue was introduced in [this](https://github.com/web3j/web3j/pull/2000) pull request.

**Comment by NickSneo** [comment]
Hey @michaelnetter ,

jc-kzg-4844 dependency was added so that users can do blob txs following support for EIP4844, let us check what we can do

**Comment by michaelnetter** [comment]
Hi @NickSneo,
I highly appreciate your efforts to support EIP-4844 in web3j.
I'm not a maven expert, but to me the cleanest solution would be to ask the developers of jc-kzg-4844 if they might consider publishing it on maven central. A fat jar (using the maven-install-plugin) that includes jc-kzg-4844 into web3j releases could be another option.

**Comment by NickSneo** [comment]
Hey @michaelnetter,
We are planning to talk to Consensys (developers of jc-kzg-4844) regarding this and moving it to maven central. Will update once we get any confirmations.

Thanks

**Comment by michaelnetter** [comment]
Hi @NickSneo,
that sounds great. Thank you for your efforts!

**Comment by mmmark0** [comment]
Hi @michaelnetter, I encountered the same error with both version 4.11.0 and 4.11.1.

I currently solved it by using the previous version 4.10.3

**Comment by sandronm** [comment]
I'm following this thread because I'm facing the same issue :)

**Comment by NickSneo** [comment]
We are in talks with Consensys team, they will be publishing it to maven central soon.
Opened up an issue to track this progress - https://github.com/Consensys/jc-kzg-4844/issues/42

**Comment by NickSneo** [comment]
Thanks for confirming @michaelnetter 
Plz use web3j >=4.12.0 for build without Consensys repo dependency
