### ISSUE TITLE
Quick Start command not working

### ISSUE THREAD

**Issue by jonathan-tan-partior** [hyperledger/web3j#2040]
# _Bug_title_
Quick start command to get web3j CLI is not working 

## Steps To Reproduce
Run quick start command `curl -L get.web3j.io | sh && source ~/.web3j/source.sh`

### Expected behavior
web3j CLI is installed

### Actual behavior
error noted : "Looks like there was an error while trying to download web3j"
![image](https://github.com/hyperledger/web3j/assets/97083012/ac048c48-d88b-4bf7-ad53-d020a4f2aae2)

## Environment
_Describe the environment in which the issue occurs_
- Web3j version - not installed
- Java or Android version - openjdk 17.0.10 2024-01-16 LTS
- Operating System - Ubuntu 20.04.6 LTS

**Comment by NickSneo** [comment]
This has been fixed.
https://github.com/hyperledger/web3j-installer/pull/14
