### ISSUE TITLE
Error: Stack too deep.

### ISSUE THREAD

**Issue by aichemzee** [hyperledger/web3j#2041]
# Error: Stack too deep.
I have a web3j project and I'm trying to import an already existing contract for interaction, but the compilation fails with the error:
```
Error: Stack too deep. Try compiling with --via-ir (cli) or the equivalent viaIR: true (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
```
## Steps To Reproduce
Use more than 16 local vars

### Expected behavior
compilation error can be fixed by passing the `viaIR = true` to `solc`.

I have a gradle project. Is there a quick way to configure this flag in my project? If not can someone point me to where the compilation happens in the plugin so that I can add the flag in the solc command locally?

Thanks.

**Comment by NickSneo** [comment]
The compilation happens using web3j-solidity-gradle plugin which uses web3j-sokt.
Another thing you can do is compile contracts using solc and place the .abi and .bin files in the required directory to just generate the java wrappers and not compile solidity files.

**Comment by aichemzee** [comment]
I was able to move past this by adding a flag --via-ir in the plugin.
Diff for someone who comes across this error: https://github.com/hyperledger/web3j-solidity-gradle-plugin/compare/main...aichemzee:web3j-solidity-gradle-plugin:main
