### ISSUE TITLE
Fail to install web3j cli on Linux

### ISSUE THREAD

**Issue by hochi-ho-partior** [hyperledger/web3j#2044]
# Fail to install web3j cli on Linux
Following the web3j official documentation page [here](Looks like there was an error while trying to download web3j) to install cli results an error "Looks like there was an error while trying to download web3j"

## Steps To Reproduce
On Ubuntu, run `curl -L get.web3j.io | sh && source ~/.web3j/source.sh` 

### Expected behavior
the installation script shall download the latest release from web3j repo and install

### Actual behavior
the following error shows  `Downloading Web3j ... Looks like there was an error while trying to download web3j`

## Environment
- Web3j version latest
- Java or Android version does not matter
- Operating System Ubuntu

**Comment by NickSneo** [comment]
@hochi-ho-partior Thanks for spotting this, it is due to recent migration of repo from web3j org to hyperledger.
Closing as PR is merged
