### ISSUE TITLE
TypeEncoder.encode(new DynamicBytes(value)) response is not the same as the contract

### ISSUE THREAD

**Issue by iranran** [hyperledger/web3j#2077]
# _Bug_title_
TypeEncoder.encode(new DynamicBytes(value)) response is not the same as the contract

## Steps To Reproduce
TypeEncoder.encode(new DynamicBytes(value))

value = 0x5c1fea88e6bbbec81a62df92d57cbae3a24315a04787e90e261a4515b6ee87507b271273c487e990ab9f5fc81be377f4a428a8f16eb95aedc19591ea6f5e4fad1b

web3j response: 00000000000000000000000000000000000000000000000000000000000000415c1fea88e6bbbec81a62df92d57cbae3a24315a04787e90e261a4515b6ee87507b271273c487e990ab9f5fc81be377f4a428a8f16eb95aedc19591ea6f5e4fad1b00000000000000000000000000000000000000000000000000000000000000

and the response value can not be decoded by solidity contract

    function encodetest(bytes memory value) external pure returns(bytes memory) {
        return abi.encode(vaule);
    }

the contract response: 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000415c1fea88e6bbbec81a62df92d57cbae3a24315a04787e90e261a4515b6ee87507b271273c487e990ab9f5fc81be377f4a428a8f16eb95aedc19591ea6f5e4fad1b00000000000000000000000000000000000000000000000000000000000000

**Comment by junsung-cho** [comment]
This issue does not appear to be a bug. If you want to see the same result as the contract response, try calling `DefaultFunctionEncoder.encodeParameters()`.

**Comment by kkkmmmsk** [comment]
that works thx
