### ISSUE TITLE
Impact of removing totalDifficulty from block info

### ISSUE THREAD

**Issue by makkanlover** [hyperledger/web3j#2106]
The go-ethereum release notes v1.14.11 suggest that totalDifficulty will be removed from the Block parameters.
https://github.com/ethereum/go-ethereum/pull/30386

I apologize if I'm wrong, but I think that if this release is applied, block information may not be available through web3j.

Actual implementation
https://github.com/hyperledger/web3j/blob/86df48c8414513f6b3109ce8e783bd2c724a9fa4/core/src/main/java/org/web3j/protocol/core/methods/response/EthBlock.java#L329

I would like to know if the removal of totalDifficulty will have any impact, and if so, when the issue will be addressed.

**Comment by makkanlover** [comment]
I used this endpoint to check whether it would still work even if totalDifficulty was gone.
https://ethereum-sepolia-rpc.publicnode.com

As a result, it worked without any problems, so I will close this issue.

**Comment by 1329576606** [comment]
java.lang.RuntimeException: com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.83, class org.web3j.protocol.core.methods.response.EthBlock$Block, method : getTotalDifficulty
